#' Heatmap of H matrix for Joint NMF Visualization
#'
#' This function is designed to allow you to visualize the weights of the H matrix
#' from the output of the RcppML package. By specifying group labels in the function you can
#' easily see how your sample weights relate to variables of interest
#'
#' The primary input is an nmf object from the RcppML::nmf function. You can also specify labels
#' of interest, which should be in a single vector or list of vectors and aligned to the H
#' matrix. If you'd like to specify colors for the labels, you can also do so in a single vector
#' or list. Refer to the pheatmap function for other parameters to further customize the heatmap.
#'
#' @param model NMF object generated by RcppML
#' @param group_labels Sample annotations for the heatmap. Input can be a vector or list of vectors
#'  properly aligned to samples in your H matrix.
#' @param group_colors If you want to manually specify colors for the row annotations. Input
#' can be a vector or a list of vectors
#' @param show_rownames Show feature names in heatmap, default to FALSE
#' @param cluster_cols Clustering of NMF components, default to FALSE
#' @param cluster_rows Clustering of Samples, default to TRUE
#' @param clustering_method Heatmap clustering method, default to ward.D2, options from pheatmap
#' @param main Heatmap title
#' @param cutree_rows Specify number of sample clusters in the heatmap
#' @param ... Arguments can be passed to the pheatmap function
#' @return Heatmap of H (Sample) weights matrix
#' @import pheatmap
#' @export

H_heatmap <- function(model,
group_labels = NULL,
group_colors = NULL,
show_rownames = FALSE,
cluster_cols = FALSE,
cluster_rows = TRUE,
clustering_method = "ward.D2",
main = "Heatmap of Samples, H matrix",
cutree_rows = 4,
...) {

  # Extract H matrix
  H <- model$h
  H_flip <- t(H)

  # Handle row annotations
  row_anno <- NULL
  ann_colors <- list()

  if (!is.null(group_labels)) {
    # Check if group_labels is already a data frame
    if (is.data.frame(group_labels)) {
      row_anno <- group_labels
    }
    # Check if group_labels is a list of vectors
    else if (is.list(group_labels) && !is.null(names(group_labels))) {
      row_anno <- as.data.frame(group_labels)
    }
    # If group_labels is a single vector
    else {
      row_anno <- data.frame(Group = group_labels)
      names(row_anno) <- "Group"
    }
  }

  # Handle color specifications
  if (!is.null(group_colors)) {
    # Check if group_colors is a list of color mappings
    if (is.list(group_colors)) {
      ann_colors <- group_colors
    }
    # If group_colors is a named vector for a single annotation
    else if (!is.null(names(group_colors))) {
      if (!is.null(row_anno) && ncol(row_anno) == 1) {
        ann_colors[[names(row_anno)[1]]] <- group_colors
      } else {
        ann_colors[["Group"]] <- group_colors
      }
    }
  }

  # Create the heatmap
  pheatmap::pheatmap(H_flip,
                     show_colnames = TRUE,
                     show_rownames = show_rownames,
                     cluster_cols = cluster_cols,
                     cluster_rows = cluster_rows,
                     clustering_method = clustering_method,
                     annotation_row = row_anno,
                     annotation_colors = ann_colors,
                     main = main,
                     cutree_rows = cutree_rows,
                     ...)
}
